# Generated by Django 5.2.6 on 2025-09-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='foo',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
