# Generated by Django 5.2.6 on 2025-09-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_foo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='foo',
        ),
    ]
